services:
  - type: web
    name: cindral-website
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: false
